huantrinh1802/m_taskwarrior_d.nvim

README.md

- Removed 'jq' from required dependencies
- Added version for 'm_taskwarrior_d.nvim'
- Updated the explanation for `:TWToggle` command
- Modified QueryView example to correct the query string

[modify] Update README and plugin dependencies

---

README.md
lua/m_taskwarrior_d/task.lua
lua/m_taskwarrior_d/utils.lua

- Use double quotes for strings in task.lua
- Add "export" option to "task depends" command in get_blocked_tasks_by function
- Simplify result processing in get_tasks_by function by extracting json decoding to external function
- Remove redundant json decoding in update_related_tasks_statuses function in utils.lua
- Simplify dependencies assignment in for-loop of update_related_tasks_statuses function

[fix] Fixed toggle status and refactor task and utils modules

---

lua/m_taskwarrior_d/task.lua
lua/m_taskwarrior_d/utils.lua

- Changed task dependencies command from "task depends:%s export" to "task depends .has:%s export"
- Revised the final status calculation in tasks to more accurately reflect status based on task occurrences.

[fix+modify] Update task dependencies command and improve task status calculation logic

---

README.md
lua/m_taskwarrior_d/init.lua

- Defined 'start_scratch(query)'
- Modified 'toggle_saved_queries(type)' to accomodate 'split'
- Updated concealTaskQuery logic
- Created new user commands 'TWQueryTasks', 'TWScratchShow', 'TWScratchHide'
close #17

[dev] Added scratch buffer for task queries

---

README.md

- Modified the format for creating queries in TaskWarrior
- Previous format was `[name of the query] | [the query]`
- New format is `[name of the query] | [filters] | [report]`, without including `[` and `]` in the actual query

fix(README): modify query format instruction

---

README.md

Corrected the installation code in README.md.
When I used the Installation code as is, lazy.nvim caused an installation error.
```diff
{
- "huantrinh1802/m_taskwarrior_d.nvim/"
+ "huantrinh1802/m_taskwarrior_d.nvim"
-- ...
}
```
It appears that lazy.nvim is sensitive to trailing slashes.

Fix installation code in README.md

---

lua/m_taskwarrior_d/init.lua
lua/m_taskwarrior_d/utils.lua

- Ensure an extra empty string is inserted into the `markdown` variable within `M.query_tasks()`.
- Modify the condition in `M.delete_scoped_tasks` to account for lines equal to `nil` or those that do not match `M.checkbox_pattern.lua`.
- Change the starting line for deletion operation from `start_line - 1` to `start_line` to correctly scope deletion of tasks.
close #39

fix: update query task and its deletion logic

---

lua/m_taskwarrior_d/utils.lua

- Updated matching pattern for 'query' to replace single quotes with double
- Added logic to extract UUID from the next line and add to 'tasks'
- Modified the while loop condition and blocktermination check to handle edge cases
- Optimized execution of 'taskwarrior' command by correcting string concatenation
- Refactored variable increment and assignment process for improved readability
Close #44

fix: corrected logic in apply_context_data function

---

lua/m_taskwarrior_d/init.lua
lua/m_taskwarrior_d/ui.lua

- Added `floating_buffer_exit_keys` in `config` which contains keys to close floating buffer.
- Modified `close` attribute in `toggle_saved_queries` function to use keys from `config.floating_buffer_exit_keys`.
- Implemented `set_config` function in `ui.lua` to update the configuration options.
- Changed attribute `enter` in `trigger_hover` function from `false` to `true`.
- Restructured `trigger_hover` function to use keys from `config.close_floating_buffer` for closing the buffer.
close #36

feat: Add configurable closing keymap

---

lua/m_taskwarrior_d/init.lua

- Renamed 'floating_buffer_exit_keys' to 'close_floating_buffer'
- Updated references to 'floating_buffer_exit_keys' with the new name 'close_floating_buffer' in toggle_saved_queries function

fix: Rename floating buffer key configurations

---

lua/m_taskwarrior_d/init.lua
lua/m_taskwarrior_d/ui.lua
lua/m_taskwarrior_d/utils.lua

- Renamed 'fields_order' to 'task_view_fields_order' and 'close_floating_buffer' to 'close_floating_window' to enhance code clarity
- Adjusted 'delete_scoped_tasks' function logic to handle edge cases when next line is not empty
- Switched all instances using 'fields_order' and 'close_floating_buffer' to the new variable names.

feat: modify key variable names and enhance deletion function

---

lua/m_taskwarrior_d/init.lua

- Changed update_current_task method in m_taskwarrior_d/init.lua to handle range of lines
- Added a range to the TWUpdateCurrent command to manage multiple update at once
- Updated the method to loop over selected lines and perform update
- This enables updating multiple tasks at once instead of a single task at a time

feat: Upgrade TWUpdateCurrent task update functionality in Taskwarrior

---

README.md
lua/m_taskwarrior_d/init.lua
lua/m_taskwarrior_d/task.lua
lua/m_taskwarrior_d/utils.lua

- Modified the 'status_map' to switch 'started' status to 'active'
- Updated 'modify_task_status' function to handle 'active' status
- Calculated 'active' task count in 'calculate_final_status' function
- Updated 'add_or_sync_task' and 'render_tasks' function to handle 'active' status+

feat: replace 'started' status with 'active' in task management

---

lua/m_taskwarrior_d/init.lua
lua/m_taskwarrior_d/utils.lua

This PR makes it possible to configure the checkbox prefix and suffix.
Example:
``` lua
require("m_taskwarrior_d").setup({
checkbox_prefix = "(",
checkbox_suffix = ")",
})
```

Make it possible to configure the checkbox prefix and suffix

---

README.md
lua/m_taskwarrior_d/init.lua
lua/m_taskwarrior_d/utils.lua

- README.md:
- Added checkbox prefix and suffix configuration.
- Introduced `default_list_symbol` for list items.
- lua/m_taskwarrior_d/init.lua:
- Added `default_list_symbol` configuration to the module's config.
- lua/m_taskwarrior_d/utils.lua:
- Updated render_tasks function to use `default_list_symbol` for list items.

[feat] add default list symbol configuration

---

README.md
lua/m_taskwarrior_d/init.lua
lua/m_taskwarrior_d/utils.lua

- Updated README.md with markdown.nvim plugin information and configuration tips for usage with obsidian.nvim.
- Added comment_prefix and comment_suffix configuration options to lua/m_taskwarrior_d/init.lua.
- Enhanced sync_tasks and view_task functions to handle new comment configurations.
- Fixed minor formatting and alignment issues in lua/m_taskwarrior_d/init.lua.
- Improved encoding patterns for both Lua and Vim in lua/m_taskwarrior_d/utils.lua.
close #66

[modify] Add markdown.nvim plugin integration and comment configurations

---

lua/m_taskwarrior_d/init.lua

- Added missing capture group to string.match function call in `TWQueryTasks` command.

[fix] correct pattern matching in TWQueryTasks command

---

lua/m_taskwarrior_d/init.lua
lua/m_taskwarrior_d/utils.lua

- Updated patterns in init.lua to conditionally include comment prefix and suffix based on configuration.
- Updated utils.lua for proper matching and rendering of task patterns with optional comment prefix and suffix.
- Fixed multiple regex pattern matching to return additional captures.
- Ensure apply_context_data terminates if it’s the last line in the buffer.
close #70

fix: handle optional comment prefix and suffix in patterns

---

lua/m_taskwarrior_d/init.lua

Updated the `M._config["task_query_pattern"].lua` to correctly apply the `comment_suffix_encoded.lua` instead of `comment_suffix_encoded.vim`, ensuring proper handling of comment suffixes in Lua patterns.

fix(init.lua): correct comment suffix encoding for Lua patterns

---

lua/m_taskwarrior_d/utils.lua

- Added missing capture group in string.match call in extract_uuid function
close #74

fix: Correct pattern matching in extract_uuid functiond

---

README.md
lua/m_taskwarrior_d/init.lua

I added this new configuration because in my editor every time I wanted to open a Markdown file, which may or may not have something to do with task warrior, it took a long time to enter the buffer. I also added an event to delete what is loaded in the `TWConceal` group when it exits the buffer.
Furthermore, I also changed it to not use `nvim_exec` because it is deprecated.

Added new configuration for the file pattern
